[workspace]
authors = ["tokoko <togurgenidze@gmail.com>"]
channels = ["conda-forge"]
name = "oidc-init"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gradle = ">=9.3.1,<10"
openjdk = "17.*"
